id: P006870
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN1328
  title: རྟ་དབང་བཀའ་འགྱུར་དཀར་ཆག
  author: ''
  volumes:
    56db6c023d41449ea266fbb0c0a3bd21:
      image_group_id: I3CN1330
      title: ''
      volume_number: 1
      total_pages: 58
      base_file: v001.txt
